### ISSUE TITLE
Zero-arg functions are treated differently than functions with args

### ISSUE THREAD

**Issue by paulmelnikow** [brunolange/artifax#5]
Hi Bruno, and thanks for publishing this interesting library! I'm using Artifax in a compute framework. It surfaces a Python compute graph to a web application. The application maintains a data store, and when it wants something computed makes a request into an AWS Lambda function which runs the Python code, passing in its dependencies which are used to initialize the Artifax object.

Since I'm attempting to build a generalized compute framework, I'd like to treat compute nodes the same, whether or not they have any dependencies.

I'm running into a confusing behavior in Artifax, which is that currently functions with no args are not evaluated. Instead, the solver passes them through.

For example, given these artifacts:

```py
build({
  'a': 42,
  'b': lambda a: a+1,
  'c': lambda: 25
})
```

This is the observed result:

```py
{ 'a': 42, 'b': 43, 'c': functools.partial(<function <lambda> at 0x7f8b78165ca0>) }
```

Whereas I'd like to have this result:

```py
{ 'a': 42, 'b': 43, 'c': 25 }
```

I can't really think of a reason why `'c'` shouldn't be evaluated. If there is some use case I'm not thinking of, where not evaluating is desirable, I think it should be opt-in rather than a default.

What do you think about changing this behavior? I'd be happy to make a PR.

**Comment by brunolange** [comment]
Hi Paul, version 0.3 has just been published to PyPI and nullary functions will now be automatically evaluated:

```python
>>> from artifax import build
>>> build({"a": 42, "b": lambda a: a+1, "c": lambda: 25})
{'a': 42, 'b': 43, 'c': 25}
```

Please give it a try and let me know if you run into any issues.
